### ISSUE TITLE
Node Module Errors 

### ISSUE THREAD

**Issue by ghost** [ibm-wch/sample-sites-pzn#1]
Unable to run npm install.

**Comment by ThomasHurek** [comment]
@tangentkitty Can you please paste the error you are getting? I verified it and did not receive any issues. Which version of node are you using?

**Comment by rywilson-ibm** [comment]
@tangentkitty can you also provide the details of the version of Node/npm you're using

**Comment by ghost** [comment]
@rywilson-ibm @ThomasHurek . I am using node v8.0 I am getting the attached error. Also, when I delete the .npmrc files it says the version for ibm-wch-sdk-ng cannot be found. 
<img width="934" alt="screen shot 2018-10-23 at 11 03 54 am" src="https://user-images.githubusercontent.com/26321221/47337919-8f82bc80-d6b3-11e8-8877-cad0b45475b7.png">

**Comment by mburati** [comment]
@tangentkitty try removing the line setting the old internal devlab repo registry setting, in the .npmrc file instead of removing the whole file.  That first line should not have been included in the .npmrc file in this repo.    Also, it looks like you'll need to change the dependency for ibm-wch-sdk-ng to 1.0.771 which is the closest public repo version to 1.0.759 that it had been referencing.

@llpomerl @ThomasHurek @rywilson-ibm - this sample should be retested, after updating for the above issues.

**Comment by mburati** [comment]
Update.  I've removed the first line of the .npmrc file, that was referring to a registry you cannot get to and bumped the version of ibm-wch-sdk-ng* up to 1.0.771 since 1.0.759 is not in the public registry.  You should just be able to pick up the latest version of .npmrc and package.json now.

**Comment by ghost** [comment]
Please update package.json to "ibm-wch-sdk-cli": "1.0.771" in devDependencies. Now I am able to start the application. However I am not getting the components. This is how the application looks.

Also these are the errors I get, 


WARNING in ./src/app/wchHeader/wchHeader.component.ts
134:50-66 "export 'RenderingContext' was not found in 'ibm-wch-sdk-ng'

WARNING in ./src/app/wchHeader/wchHeader.component.ts
134:86-102 "export 'RenderingContext' was not found in 'ibm-wch-sdk-ng'

WARNING in ./src/app/wchHeader/wchHeader.component.ts
135:57-73 "export 'RenderingContext' was not found in 'ibm-wch-sdk-ng'

WARNING in ./src/app/wchHeader/wchHeader.component.ts
135:93-109 "export 'RenderingContext' was not found in 'ibm-wch-sdk-ng'

<img width="1440" alt="screen shot 2018-10-23 at 8 19 19 pm" src="https://user-images.githubusercontent.com/26321221/47369419-40637880-d701-11e8-93ae-43c06068cdb3.png">

**Comment by ThomasHurek** [comment]
@tangentkitty Did you configure the CORS in WCH - e.g. * ?
<img width="408" alt="image" src="https://user-images.githubusercontent.com/7836735/47381100-1db76c80-d6cd-11e8-8225-9ae128ddd6cd.png">

**Comment by ghost** [comment]
@ThomasHurek - I missed to add the domains. It's working perfectly fine now. Thank you all for your immediate assistance
